### ISSUE TITLE
Travis CI failing in multiple ways

### ISSUE THREAD

**Issue by murrayrm** [python-control/Slycot#17]
Travis CI is consistently failing on slycot builds.  Here is a summary of the [Travis CI build failures from PR #13](https://travis-ci.org/python-control/Slycot/builds/328513604?utm_source=github_status&utm_medium=notification):

* Travis CI succeeds testing `slycot` in python 2.7
* Travis CI fails in testing `slycot` in python 3.3, due to inability of conda to resolve dependencies
3.4, 3.5
* Travis CI success in testing `python-control` in python 2.7, 3.5, 3.6 ([test results](https://travis-ci.org/python-control/python-control/builds/328493519?utm_source=github_status&utm_medium=notification))

The dependency issue in python 3.3 and 3.4 gives the following error:
```
conda build --python "$TRAVIS_PYTHON_VERSION" conda-recipe
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
Attempting to finalize metadata for slycot
INFO:conda_build.metadata:Attempting to finalize metadata for slycot
Solving environment: failed

failed to get install actions, retrying.  exception was: The following specifications were found to be in conflict:
  - numpy[version='>=1.13.3'] -> python[version='>=2.7,<2.8.0a0'] -> readline=7
  - numpy[version='>=1.13.3'] -> python[version='>=2.7,<2.8.0a0'] -> tk=8.6
  - python=3.3
```

A different error occurs in python 3.5.  The various dependencies seem to work OK there, but there is an error when building the slycot library:
```
/usr/bin/gfortran -Wall -g -shared <long list of files> -llapack -lblas -lpython3.5m -lgfortran -o build/lib.linux-x86_64-3.5/slycot/_wrapper.cpython-35m-x86_64-linux-gnu.so
/usr/bin/ld: cannot find -llapack
/usr/bin/ld: cannot find -lblas
/usr/bin/ld: cannot find -lpython3.5m
collect2: error: ld returned 1 exit status
```
This must be some sort of error in the build environment.

The above build issues are not a problem in my local environment (MacOS 10.12.6), so likely something having to do with the Travis CI build environment (which is done under Ubuntu Trusty, I think).

Finally, there is yet a different error in PR #13, where the issue there appears to be in `testMinrealBrute`, which generates the following error:
```
FAIL: testMinrealBrute (control.tests.minreal_test.TestMinreal)
Traceback (most recent call last):
  File "/Users/murray/Dropbox/macosx/src/python-control/murrayrm/control/tests/minreal_test.py", line 62, in testMinrealBrute
    raise e
  File "/Users/murray/Dropbox/macosx/src/python-control/murrayrm/control/tests/minreal_test.py", line 57, in testMinrealBrute
    ht1.den[0][0], ht2.den[0][0])
  File "/Users/murray/Dropbox/macosx/src/python-control/murrayrm/control/tests/minreal_test.py", line 35, in assert_numden_almost_equal
    np.testing.assert_array_almost_equal(n1, n2)
  File "/Users/murray/anaconda/envs/test_slycot/lib/python3.6/site-packages/numpy/testing/utils.py", line 962, in assert_array_almost_equal
    precision=decimal)
  File "/Users/murray/anaconda/envs/test_slycot/lib/python3.6/site-packages/numpy/testing/utils.py", line 715, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals

(shapes (3,), (4,) mismatch)
 x: array([ -1.33214 , -10.368378, -13.703545])
 y: array([ -1.33214 , -13.297947, -36.505109, -30.136079])
```

I'm going to try to get a working version of all of this up and going, so that we can get the integration tests working again.  Will document progress here.

**Comment by murrayrm** [comment]
PR #19 addresses the issues above.  

Regarding the problem with `testMinrealBrute`: this seems to only occur if you include `conda-forge` as a channel before running `conda build`.  What I have done instead is to use `conda-forge` just to install `lapack` and use the standard channels for everything else.  Seems to work.

Once PR #19 is accepted, we can close this issue.

**Comment by murrayrm** [comment]
PR #19 accepted, fixes this issue.
