### ISSUE TITLE
Segmentation Fault on ARM MacOS

### ISSUE THREAD

**Issue by SeyedMohamadMoosavi** [python-control/Slycot#186]
Installed the package using conda in a clean conda environment on MacOS Ventura M1 Pro Chip.

`conda install -c conda-forge control slycot`

However, I get segmentation fault after importing control:
`import control`
output is:
> [1]    11822 segmentation fault  python

**Comment by murrayrm** [comment]
@SeyedMohamadMoosavi FYI, I have moved this to slycot.

@bnavigator @roryyorke Any ideas about what might be happening on MacOS Ventura?

**Comment by bnavigator** [comment]
Probably another problem with the cross-compilation for macOS arm on the conda-forge/slycot-feedstock. Maybe @isuruf or someone else from @conda-forge/help-osx-arm64 has an idea how to debug this.

**Comment by bnavigator** [comment]
https://github.com/conda-forge/simpleitk-feedstock/pull/27 mentions our struggle with the slycot-feedstock and has yet another fix.

**Comment by bnavigator** [comment]
@SeyedMohamadMoosavi do you get a similar segmentation fault when you install an older slycot version with `conda install slycot=0.5.0.0` ([osx-arm64/slycot-0.5.0.0-py39hb3be402_2.tar.bz2](https://anaconda.org/conda-forge/slycot/0.5.0.0/download/osx-arm64/slycot-0.5.0.0-py39hb3be402_2.tar.bz2))?

**Comment by SeyedMohamadMoosavi** [comment]
yes, I get the same error.

**Comment by bnavigator** [comment]
Can you please try the new slycot 0.5.3 to be published on conda-forge shortly?

Also, please make sure to install everything from conda-forge. No mixins of packages from "normal" anaconda.

**Comment by SeyedMohamadMoosavi** [comment]
I get the same error. 
What I did:
`conda create -n pycontrol python=3.9`
`conda activate pycontrol`
`conda install -c conda-forge slycot=0.5.3`
`conda install -c conda-forge control`

**Comment by bnavigator** [comment]
This would be a command to create a conda environent with strictly conda-forge packages, no packages from main:

```
conda create \
     --name control-env \
     --channel conda-forge \
     --strict-channel-priority \
     control slycot
```

**Comment by murrayrm** [comment]
I was able to install slycot from conda-force on an M1 mac, but running MacOS 12.6.2 (Monterey).  So it might be something in Ventura.

**Comment by bnavigator** [comment]
There is also still a possible difference between Conda/Python for native Arm and with Rosetta, if I am not mistaken?

**Comment by bnavigator** [comment]
https://towardsdatascience.com/how-to-manage-conda-environments-on-an-apple-silicon-m1-mac-1e29cb3bad12

**Comment by bnavigator** [comment]
Hi @bdube-jpl, thanks for the extensive info!

I am fetching the core right now. Hopefully I can analyze it later this week.

Regarding pip: The new standard way is to build wheels in an isolated environment which needs all the build requirements as wheels. There is the `--no-build-isolation` flag to disable that.

Did you try the conda recipe from the repository?

Also there is https://github.com/conda-forge/slycot-feedstock/blob/main/recipe/build.sh for a reference of tweaks

The displayed error is because of missing numpy files. They belong to f2py. Without the build-isolation, cmake should be able to find the files from the conda environment.

**Comment by bdube-jpl** [comment]
The actual compilation worked (I assume), but there is some setup issue still.  
```
 copying _skbuild/macosx--arm64-3.10/setuptools/lib.macosx--arm64-cpython-310/slycot/synthesis.py -> _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/slycot
  copied 27 files
  running install_egg_info
  Copying slycot.egg-info to _skbuild/macosx--arm64-3.10/setuptools/bdist.macosx--arm64/wheel/slycot-0.5.4.dev4+g773c893-py3.10.egg-info
  running install_scripts
  copied 0 files
  Traceback (most recent call last):
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/setuptools/build_meta.py", line 413, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
      self.run_setup()
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 61, in <module>
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/skbuild/setuptools_wrap.py", line 754, in setup
      return setuptools.setup(**kw)
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
      return distutils.core.setup(**attrs)
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/setuptools/dist.py", line 1213, in run_command
      super().run_command(command)
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/skbuild/command/bdist_wheel.py", line 31, in run
      super().run(*args, **kwargs)
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 362, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 280, in get_tag
      plat_name = get_platform(self.bdist_dir)
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 51, in get_platform
      result = calculate_macosx_platform_tag(archive_root, result)
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/wheel/macosx_libfile.py", line 399, in calculate_macosx_platform_tag
      base_version = tuple(int(x) for x in base_version.split("."))
    File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/wheel/macosx_libfile.py", line 399, in <genexpr>
      base_version = tuple(int(x) for x in base_version.split("."))
  ValueError: invalid literal for int() with base 10: ''
  error: subprocess-exited-with-error
```
I can try the conda recipe if you'd like, too

**Comment by bnavigator** [comment]
Yes please try the conda recipe.

Looks like you have encountered a bug in either `wheel` or `scikit-build` regarding an expected but not existing macosx_platform_tag.

Ping @henryiii

**Comment by henryiii** [comment]
I fixed something lightly related to this recently, I'm guessing the above is with the most recent version of scikit-build? Don't think it would fix exactly this (why is it not getting any information about the platform tag? I expect all packaging starts breaking if that's empty - in fact yes, this is crashing before it even gets to scikit-build's customizations, so my recent fix for valid platform tags wouldn't even get hit).

I'm guessing you are trying to cross-compile, and are setting up an invalid environment? Conda-forge's environment setup is complex. By hand, it's much easier to build a cross-compiled wheel (such as via cibuildwheel). Conda is a hacked-together mess of scripts that kind of needs perfect setup to build.

**Comment by bnavigator** [comment]
Thanks for the inpit @henryiii, I fully agree with your assessment that conda is too brittle.

@bdube-jpl is actually trying to natively compile on ARM as opposed to cross-compile like conda-forge does. Either way it is hard to get a functioning compiled package.

**Comment by bdube-jpl** [comment]
👋 @henryiii 

I think it may be an issue in skbuild.  I have v0.16.6.  Here's a tree of `_skbuild`:

```
_skbuild/
└── macosx--arm64-3.10
    ├── cmake-build
    │   ├── CMakeCache.txt
    │   ├── CMakeFiles
    │   │   ├── 3.25.2
    │   │   │   ├── CMakeCCompiler.cmake
    │   │   │   ├── CMakeDetermineCompilerABI_C.bin
    │   │   │   ├── CMakeDetermineCompilerABI_Fortran.bin
    │   │   │   ├── CMakeFortranCompiler.cmake
    │   │   │   ├── CMakeSystem.cmake
    │   │   │   ├── CompilerIdC
    │   │   │   │   ├── CMakeCCompilerId.c
    │   │   │   │   ├── a.out
    │   │   │   │   └── tmp
    │   │   │   └── CompilerIdFortran
    │   │   │       ├── CMakeFortranCompilerId.F
    │   │   │       ├── a.out
    │   │   │       └── tmp
    │   │   ├── CMakeDirectoryInformation.cmake
    │   │   ├── CMakeError.log
    │   │   ├── CMakeOutput.log
    │   │   ├── CMakeRuleHashes.txt
    │   │   ├── Makefile.cmake
    │   │   ├── Makefile2
    │   │   ├── TargetDirectories.txt
    │   │   ├── _f2py_runtime_library.dir
    │   │   │   ├── DependInfo.cmake
    │   │   │   ├── Users
    │   │   │   │   └── bdube
    │   │   │   │       └── miniconda3
    │   │   │   │           └── envs
    │   │   │   │               └── controlcrashselfbuild
    │   │   │   │                   └── lib
    │   │   │   │                       └── python3.10
    │   │   │   │                           └── site-packages
    │   │   │   │                               └── numpy
    │   │   │   │                                   └── f2py
    │   │   │   │                                       └── src
    │   │   │   │                                           ├── fortranobject.c.o
    │   │   │   │                                           └── fortranobject.c.o.d
    │   │   │   ├── build.make
    │   │   │   ├── cmake_clean.cmake
    │   │   │   ├── cmake_clean_target.cmake
    │   │   │   ├── compiler_depend.make
    │   │   │   ├── compiler_depend.ts
    │   │   │   ├── depend.make
    │   │   │   ├── flags.make
    │   │   │   ├── link.txt
    │   │   │   └── progress.make
    │   │   ├── cmake.check_cache
    │   │   ├── pkgRedirects
    │   │   └── progress.marks
    │   ├── CMakeSpec.json
    │   ├── CMakeTmp
    │   │   └── link_flags
    │   │       ├── gnu_ld_ignore
    │   │       │   └── MODULE
    │   │       │       └── SHARED
    │   │       │           ├── build
    │   │       │           │   ├── CMakeCache.txt
    │   │       │           │   ├── CMakeFiles
    │   │       │           │   │   ├── CMakeDirectoryInformation.cmake
    │   │       │           │   │   ├── Makefile.cmake
    │   │       │           │   │   ├── Makefile2
    │   │       │           │   │   ├── Progress
    │   │       │           │   │   │   ├── 1
    │   │       │           │   │   │   ├── 2
    │   │       │           │   │   │   ├── 5
    │   │       │           │   │   │   ├── 6
    │   │       │           │   │   │   └── count.txt
    │   │       │           │   │   ├── TargetDirectories.txt
    │   │       │           │   │   ├── cmake.check_cache
    │   │       │           │   │   ├── counter.dir
    │   │       │           │   │   │   ├── DependInfo.cmake
    │   │       │           │   │   │   ├── build.make
    │   │       │           │   │   │   ├── cmake_clean.cmake
    │   │       │           │   │   │   ├── compiler_depend.make
    │   │       │           │   │   │   ├── compiler_depend.ts
    │   │       │           │   │   │   ├── counter.c.o
    │   │       │           │   │   │   ├── counter.c.o.d
    │   │       │           │   │   │   ├── depend.make
    │   │       │           │   │   │   ├── flags.make
    │   │       │           │   │   │   ├── link.txt
    │   │       │           │   │   │   └── progress.make
    │   │       │           │   │   ├── main.dir
    │   │       │           │   │   │   ├── DependInfo.cmake
    │   │       │           │   │   │   ├── build.make
    │   │       │           │   │   │   ├── cmake_clean.cmake
    │   │       │           │   │   │   ├── compiler_depend.make
    │   │       │           │   │   │   ├── compiler_depend.ts
    │   │       │           │   │   │   ├── depend.make
    │   │       │           │   │   │   ├── flags.make
    │   │       │           │   │   │   ├── link.txt
    │   │       │           │   │   │   └── progress.make
    │   │       │           │   │   ├── number.dir
    │   │       │           │   │   │   ├── DependInfo.cmake
    │   │       │           │   │   │   ├── build.make
    │   │       │           │   │   │   ├── cmake_clean.cmake
    │   │       │           │   │   │   ├── compiler_depend.make
    │   │       │           │   │   │   ├── compiler_depend.ts
    │   │       │           │   │   │   ├── depend.make
    │   │       │           │   │   │   ├── flags.make
    │   │       │           │   │   │   ├── link.txt
    │   │       │           │   │   │   ├── number.c.o
    │   │       │           │   │   │   ├── number.c.o.d
    │   │       │           │   │   │   └── progress.make
    │   │       │           │   │   ├── pkgRedirects
    │   │       │           │   │   └── progress.marks
    │   │       │           │   ├── Makefile
    │   │       │           │   ├── cmake_install.cmake
    │   │       │           │   └── libnumber.dylib
    │   │       │           └── src
    │   │       │               ├── CMakeLists.txt
    │   │       │               ├── counter.c
    │   │       │               ├── counter.h
    │   │       │               ├── main.c
    │   │       │               ├── number.c
    │   │       │               └── number.h
    │   │       └── osx_dynamic_lookup
    │   │           └── MODULE
    │   │               └── SHARED
    │   │                   ├── build
    │   │                   │   ├── CMakeCache.txt
    │   │                   │   ├── CMakeFiles
    │   │                   │   │   ├── CMakeDirectoryInformation.cmake
    │   │                   │   │   ├── Makefile.cmake
    │   │                   │   │   ├── Makefile2
    │   │                   │   │   ├── TargetDirectories.txt
    │   │                   │   │   ├── cmake.check_cache
    │   │                   │   │   ├── counter.dir
    │   │                   │   │   │   ├── DependInfo.cmake
    │   │                   │   │   │   ├── build.make
    │   │                   │   │   │   ├── cmake_clean.cmake
    │   │                   │   │   │   ├── compiler_depend.make
    │   │                   │   │   │   ├── compiler_depend.ts
    │   │                   │   │   │   ├── counter.c.o
    │   │                   │   │   │   ├── counter.c.o.d
    │   │                   │   │   │   ├── depend.make
    │   │                   │   │   │   ├── flags.make
    │   │                   │   │   │   ├── link.txt
    │   │                   │   │   │   └── progress.make
    │   │                   │   │   ├── main.dir
    │   │                   │   │   │   ├── DependInfo.cmake
    │   │                   │   │   │   ├── build.make
    │   │                   │   │   │   ├── cmake_clean.cmake
    │   │                   │   │   │   ├── compiler_depend.make
    │   │                   │   │   │   ├── compiler_depend.ts
    │   │                   │   │   │   ├── depend.make
    │   │                   │   │   │   ├── flags.make
    │   │                   │   │   │   ├── link.txt
    │   │                   │   │   │   ├── main.c.o
    │   │                   │   │   │   ├── main.c.o.d
    │   │                   │   │   │   └── progress.make
    │   │                   │   │   ├── number.dir
    │   │                   │   │   │   ├── DependInfo.cmake
    │   │                   │   │   │   ├── build.make
    │   │                   │   │   │   ├── cmake_clean.cmake
    │   │                   │   │   │   ├── compiler_depend.make
    │   │                   │   │   │   ├── compiler_depend.ts
    │   │                   │   │   │   ├── depend.make
    │   │                   │   │   │   ├── flags.make
    │   │                   │   │   │   ├── link.txt
    │   │                   │   │   │   ├── number.c.o
    │   │                   │   │   │   ├── number.c.o.d
    │   │                   │   │   │   └── progress.make
    │   │                   │   │   ├── pkgRedirects
    │   │                   │   │   └── progress.marks
    │   │                   │   ├── Makefile
    │   │                   │   ├── cmake_install.cmake
    │   │                   │   ├── counter.so
    │   │                   │   ├── libnumber.dylib
    │   │                   │   └── main
    │   │                   └── src
    │   │                       ├── CMakeLists.txt
    │   │                       ├── counter.c
    │   │                       ├── counter.h
    │   │                       ├── main.c
    │   │                       ├── number.c
    │   │                       └── number.h
    │   ├── Makefile
    │   ├── cmake_install.cmake
    │   ├── install_manifest.txt
    │   ├── lib_f2py_runtime_library.a
    │   └── slycot
    │       ├── CMakeFiles
    │       │   ├── CMakeDirectoryInformation.cmake
    │       │   ├── _wrapper.dir
    │       │   │   ├── DependInfo.cmake
    │       │   │   ├── Users
    │       │   │   │   └── bdube
    │       │   │   │       └── miniconda3
    │       │   │   │           └── envs
    │       │   │   │               └── controlcrashselfbuild
    │       │   │   │                   └── lib
    │       │   │   │                       └── python3.10
    │       │   │   │                           └── site-packages
    │       │   │   │                               └── numpy
    │       │   │   │                                   └── f2py
    │       │   │   │                                       └── src
    │       │   │   │                                           ├── fortranobject.c.o
    │       │   │   │                                           └── fortranobject.c.o.d
    │       │   │   ├── _wrapper-f2pywrappers.f.o
    │       │   │   ├── _wrappermodule.c.o
    │       │   │   ├── _wrappermodule.c.o.d
    │       │   │   ├── build.make
    │       │   │   ├── cmake_clean.cmake
    │       │   │   ├── compiler_depend.make
    │       │   │   ├── compiler_depend.ts
    │       │   │   ├── depend.internal
    │       │   │   ├── depend.make
    │       │   │   ├── flags.make
    │       │   │   ├── fortran.internal
    │       │   │   ├── link.txt
    │       │   │   ├── progress.make
    │       │   │   └── src
    │       │   │       ├── SLICOT-Reference
    │       │   │       │   └── src
    │       │   │       │       ├── ...snip
    │       │   │       ├── XERBLA.f.o
    │       │   │       └── ftruefalse.f.o
    │       │   ├── progress.marks
    │       │   └── wrapper.dir
    │       │       ├── DependInfo.cmake
    │       │       ├── build.make
    │       │       ├── cmake_clean.cmake
    │       │       ├── compiler_depend.make
    │       │       ├── compiler_depend.ts
    │       │       └── progress.make
    │       ├── Makefile
    │       ├── _wrapper-f2pywrappers.f
    │       ├── _wrapper.cpython-310-darwin.so
    │       ├── _wrappermodule.c
    │       ├── cmake_install.cmake
    │       └── tests
    │           ├── CMakeFiles
    │           │   ├── CMakeDirectoryInformation.cmake
    │           │   └── progress.marks
    │           ├── Makefile
    │           └── cmake_install.cmake
    ├── cmake-install
    │   └── slycot
    │       ├── __init__.py
    │       ├── _wrapper.cpython-310-darwin.so
    │       ├── analysis.py
    │       ├── examples.py
    │       ├── exceptions.py
    │       ├── math.py
    │       ├── synthesis.py
    │       ├── tests
    │       │   ├── ...snip
    │       │   └── test_transform.py
    │       ├── transform.py
    │       └── version.py
    └── setuptools
        ├── bdist.macosx--arm64
        │   └── wheel
        │       ├── slycot
        │       │   ├── __init__.py
        │       │   ├── _wrapper.cpython-310-darwin.so
        │       │   ├── analysis.py
        │       │   ├── examples.py
        │       │   ├── exceptions.py
        │       │   ├── math.py
        │       │   ├── synthesis.py
        │       │   ├── tests
        │       │   │   ├── ...snip
        │       │   │   └── test_transform.py
        │       │   ├── transform.py
        │       │   └── version.py
        │       └── slycot-0.5.4.dev4+g773c893-py3.10.egg-info
        │           ├── PKG-INFO
        │           ├── SOURCES.txt
        │           ├── dependency_links.txt
        │           ├── not-zip-safe
        │           ├── requires.txt
        │           └── top_level.txt
        └── lib.macosx--arm64-cpython-310
            └── slycot
                ├── __init__.py
                ├── _wrapper.cpython-310-darwin.so
                ├── analysis.py
                ├── examples.py
                ├── exceptions.py
                ├── math.py
                ├── synthesis.py
                ├── tests
                │   ├── ... snip
                ├── transform.py
                └── version.py

76 directories, 872 files
```
The exception thrown by wheel is,
```
base_version = tuple(int(x) for x in base_version.split("."))
ValueError: invalid literal for int() with base 10: ''
```
I don't actually see anything that has a trailing period, `lib.macosx--arm64-cpython-310`, and so on.

Now, conda build.. `conda-build -c conda-forge conda-recipe` fails, due to being unable to find a suitable version of numpy.  The controlcrashselfbuild env has 1.24.1, so I'm not sure why it can't resolve a proper one.
```
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Attempting to finalize metadata for slycot
INFO:conda_build.metadata:Attempting to finalize metadata for slycot
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

Leaving build/test directories:
  Work:
 /Users/bdube/miniconda3/envs/controlcrashselfbuild/conda-bld/work
  Test:
 /Users/bdube/miniconda3/envs/controlcrashselfbuild/conda-bld/test_tmp
Leaving build/test environments:
  Test:
source activate  /Users/bdube/miniconda3/envs/controlcrashselfbuild/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
  Build:
source activate  /Users/bdube/miniconda3/envs/controlcrashselfbuild/conda-bld/_build_env


Traceback (most recent call last):
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda_build/environ.py", line 796, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
    return f(*args, **kwds)
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda/plan.py", line 470, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda/core/solve.py", line 132, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda/core/solve.py", line 175, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda/core/solve.py", line 293, in solve_final_state
    ssc = self._add_specs(ssc)
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda/core/solve.py", line 590, in _add_specs
    explicit_pool = ssc.r._get_package_pool(self.specs_to_add)
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda/resolve.py", line 553, in _get_package_pool
    pool = self.get_reduced_index(specs)
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
    return f(*args, **kwds)
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda/resolve.py", line 574, in get_reduced_index
    explicit_specs, features = self.verify_specs(explicit_specs)
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda/resolve.py", line 286, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound:
  - numpy[version='!=1.23.0,1.16.*']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 495, in main
    execute(sys.argv[1:])
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 475, in execute
    outputs = api.build(
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda_build/build.py", line 3097, in build_tree
    packages_from_this = build(metadata, stats,
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda_build/build.py", line 2049, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda_build/render.py", line 780, in expand_outputs
    for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda_build/metadata.py", line 2524, in get_output_metadata_set
    conda_packages = finalize_outputs_pass(
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda_build/metadata.py", line 870, in finalize_outputs_pass
    output_d = om.get_rendered_output(metadata.name()) or {
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda_build/metadata.py", line 2615, in get_rendered_output
    for output_ in self.get_rendered_outputs_section(
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda_build/metadata.py", line 2597, in get_rendered_outputs_section
    self._get_contents(
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda_build/metadata.py", line 1872, in _get_contents
    rendered = template.render(environment=env)
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/bdube/src/Slycot/conda-recipe/meta.yaml", line 31, in top-level template code
    - pip
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda_build/jinja_context.py", line 231, in pin_compatible
    pins, _, _ = get_env_dependencies(m, 'host', m.config.variant)
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda_build/render.py", line 132, in get_env_dependencies
    actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
  File "/Users/bdube/miniconda3/envs/controlcrashselfbuild/lib/python3.10/site-packages/conda_build/environ.py", line 798, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform osx-arm64: {"numpy[version='!=1.23.0,1.16.*']"}
```

**Comment by bnavigator** [comment]
Oh my, that stupid conda resolver.

Could you try to replace https://github.com/python-control/Slycot/blob/773c893a79abd10c2ada7c138ad7d3f3bac6480c/conda-recipe/meta.yaml#L30 with

```
    - numpy >=1.19,!=1.23.0
```
?
(https://github.com/conda-forge/slycot-feedstock/blob/a37fc29999dbf730415b35a2e39635d7eda2fc23/recipe/meta.yaml#L31)

**Comment by bnavigator** [comment]
`lib.macosx--arm64-cpython-310` is obviously missing the macos version between the `--`.

What does `sysconfig.get_platform()` return?

https://github.com/pypa/wheel/blob/bd02d4cfef1a0386a7e11f40325932cf5b4b932e/src/wheel/bdist_wheel.py#L49-51

https://github.com/pypa/wheel/blob/ad2951260b491fbe9f4b45cdd94bbdeec20962fe/src/wheel/macosx_libfile.py#L392-L471

**Comment by bdube-jpl** [comment]
sysconfig:
```
>>> import sysconfig
>>> sysconfig.get_platform()
'macosx-11.0-arm64'
```

With the modified numpy in meta.yml, the package does build and install properly, but results in the segfault on import.  The fortran compile complained about some out-of-bounds array access, so maybe that is the fundamental issue (why it seems to work in general and not on arm could easily be a difference in UB between compilers).  ~line 1354 in the log.  It may also be Numpy ABI incompatibility between 1.16 (I think it built with this anyway?) and my 1.24.1.  Usually Numpy self-detects that and prints a warning on import that the size of the array object has changed between compile and runtime though.

The attached is the log from conda-build
[condabuild.txt](https://github.com/python-control/Slycot/files/10572119/condabuild.txt)

**Comment by bnavigator** [comment]
The out of bounds  is a false positive error message, see #111.
The logs use `lib.macosx-11.0-arm64-cpython-310` and `_skbuild/macosx-11.0-arm64-3.10` so that is different from the pip build. They also say that it found numpy 1.24.1. Where do you see 1.16 except for the first 4 lines?

Thanks for trying! So we can conclude that it is not problem with the cross-compilation.

Now back to the segfault, can you run gdb or a Mac equivalent for it?

**Comment by bdube-jpl** [comment]
yes

**Comment by murrayrm** [comment]
Follow up on this thread: I recently upgraded to Ventura with M2 and was able to get python-control and Slycot all working with arm64.  Are others on this thread still having problems?  If not, we can probably close this one off.

**Comment by bnavigator** [comment]
No further feedback since. Closing.
