### ISSUE TITLE
Problem when import slycot

### ISSUE THREAD

**Issue by Scylk** [python-control/Slycot#94]
I have installed slycot, but when I try to import slycot, it comes like that:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/scylk/pycharm-community-2019.2/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/scylk/anaconda3/envs/rl/lib/python3.6/site-packages/slycot/__init__.py", line 16, in <module>
    from .analysis import ab01nd,ab05md,ab05nd,ab07nd,ab08nd, \
  File "/home/scylk/pycharm-community-2019.2/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/scylk/anaconda3/envs/rl/lib/python3.6/site-packages/slycot/analysis.py", line 21, in <module>
    from . import _wrapper
  File "/home/scylk/pycharm-community-2019.2/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ImportError: libmkl_gf_lp64.so: cannot open shared object file: No such file or directory

My python=3.6 on Ubuntu

**Comment by bnavigator** [comment]
Where did you install slycot from? Anaconda? Looks like you installed a version linked to MKL. You need to install the [non-open source Intel Math Kernel Library](https://docs.anaconda.com/mkl-optimizations/).
